/**
 * @file InventoryReport.cpp
 * @brief Implements the InventoryReport class for generating detailed inventory reports.
 */

#include "InventoryReport.h"
#include <stdexcept>

/**
 * @brief Constructs an InventoryReport for a given inventory.
 * 
 * @param inv Pointer to the Inventory object to generate the report from.
 * Prints a warning if the inventory pointer is null.
 */
InventoryReport::InventoryReport(Inventory* inv) : inventory(inv) {
    if (inv == nullptr) {
        std::cout << "Warning: Inventory is null in InventoryReport constructor\n";
    }
}

/**
 * @brief Initializes the report with a title and the current date/time.
 */
void InventoryReport::initializeReport() {
    reportTitle = "Comprehensive Inventory Status Report";
    
    std::time_t now = std::time(nullptr);
    std::tm* timeInfo = std::localtime(&now);
    
    std::stringstream dateStream;
    dateStream << std::put_time(timeInfo, "%Y-%m-%d at %H:%M:%S");
    generatedDate = dateStream.str();
}

/**
 * @brief Collects inventory data for the report.
 * 
 * Simulates data collection for total items, stock levels, and inventory value.
 */
void InventoryReport::collectData() {
    std::cout << "Collecting comprehensive inventory data..." << std::endl;
    
    reportData["TotalItems"] = "247";
    reportData["PlantsInStock"] = "189";
    reportData["SuppliesInStock"] = "58";
    reportData["LowStockItems"] = "23";
    reportData["OutOfStock"] = "7";
    reportData["TotalValue"] = "$8,425.50";
    reportData["AverageItemValue"] = "$34.11";
    reportData["InventoryTurnover"] = "2.8";
    
    std::cout << "Inventory data collection completed" << std::endl;
}

/**
 * @brief Processes the collected inventory data.
 * 
 * Calculates low stock percentage and assesses inventory risk levels.
 */
void InventoryReport::processData() {
    Report::processData();
    
    std::cout << "Performing inventory-specific data analysis..." << std::endl;
    
    int lowStock = std::stoi(reportData["LowStockItems"]);
    int totalItems = std::stoi(reportData["TotalItems"]);
    double lowStockPercentage = (static_cast<double>(lowStock) / totalItems) * 100;
    
    std::stringstream ss;
    ss << std::fixed << std::setprecision(1) << lowStockPercentage;
    reportData["LowStockPercentage"] = ss.str() + "%";
    
    if (lowStockPercentage > 20) {
        reportData["StockRisk"] = "HIGH - Consider bulk ordering";
    } else if (lowStockPercentage > 10) {
        reportData["StockRisk"] = "MEDIUM - Monitor closely";
    } else {
        reportData["StockRisk"] = "LOW - Healthy inventory levels";
    }
}

/**
 * @brief Formats the body of the inventory report.
 * 
 * @return A string containing the inventory overview, stock analysis, and recommended actions.
 */
std::string InventoryReport::formatBody() {
    std::stringstream body;
    
    body << "INVENTORY OVERVIEW:\n";
    body << std::string(40, '-') << "\n";
    body << "Total Items: " << reportData["TotalItems"] << "\n";
    body << "Plants in Stock: " << reportData["PlantsInStock"] << "\n";
    body << "Supplies in Stock: " << reportData["SuppliesInStock"] << "\n";
    body << "Total Inventory Value: " << reportData["TotalValue"] << "\n";
    body << "Average Item Value: " << reportData["AverageItemValue"] << "\n";
    body << "Inventory Turnover Rate: " << reportData["InventoryTurnover"] << "\n\n";
    
    body << "STOCK LEVEL ANALYSIS:\n";
    body << std::string(40, '-') << "\n";
    body << "Low Stock Items: " << reportData["LowStockItems"] << "\n";
    body << "Out of Stock Items: " << reportData["OutOfStock"] << "\n";
    body << "Low Stock Percentage: " << reportData["LowStockPercentage"] << "\n";
    body << "Risk Assessment: " << reportData["StockRisk"] << "\n\n";
    
    body << "RECOMMENDED ACTIONS:\n";
    body << std::string(40, '-') << "\n";
    body << "1. Restock out-of-stock items immediately\n";
    body << "2. Review low-stock items for reorder planning\n";
    body << "3. Consider seasonal demand for upcoming quarters\n";
    body << "4. Evaluate supplier performance for critical items\n";
    body << "5. Optimize inventory layout for fast-moving items\n";
    
    return body.str();
}

/**
 * @brief Adds a footer to the inventory report.
 * 
 * @return A string containing contact information and next audit details.
 */
std::string InventoryReport::addFooter() {
    std::stringstream footer;
    footer << "\n" << std::string(50, '=') << "\n";
    footer << "INVENTORY MANAGEMENT CONTACTS:\n";
    footer << "• Inventory Manager: manager@gardencenter.com\n";
    footer << "• Procurement: procurement@gardencenter.com\n";
    footer << "• Emergency Orders: emergency@gardencenter.com\n";
    footer << std::string(50, '=') << "\n";
    footer << "Next scheduled inventory audit: 30 days\n";
    footer << "Report generated by Automated Inventory System v2.1";
    return footer.str();
}

/**
 * @brief Returns the type of the report.
 * 
 * @return A string indicating this is an "Inventory" report.
 */
std::string InventoryReport::getReportType() const {
    return "Inventory";
}
